source $HOME/.aliases
source $HOME/.colorbash

EDITOR=vim

function __last_rc () {
    RC=$?
    if [ "$RC" -ne 0 ]; then
        echo -e "${txtpur}${RC}${txtylw}:"
    fi
}

LAST_RC='$(__last_rc)'
PS1="\\[$txtpur\]\t\[$txtrst\]:\[$txtylw\]\u\[$txtrst\]:\[$txtgrn\]\w:$LAST_RC\!\[$txtrst\]> "

export HISTTIMEFORMAT="%d/%m/%y %T "

export PS1
export EDITOR

